version: "3.8"

services:
    postgres:
        image: postgres:14

        container_name: my_postgres2
        environment:
            POSTGRES_USER: mariama
            POSTGRES_PASSWORD: mariama
            POSTGRES_DB: mariama_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: